mc_ver=1.21.1

mod_name=Just Unicorns
mod_authors=["Angelin01"]
mod_id=justunicorns
mod_version=2025.8.23
group=com.angelin01.justunicorns
license=MIT
credits=
description=A Minecraft mods that adds just unicorns (ok, maybe some minor other stuff too)

manifold_version=2025.1.14

org.gradle.jvmargs=-Xmx6G
org.gradle.parallel=true
org.gradle.caching=true
#org.gradle.configuration-cache=true
org.gradle.java.installations.auto-download=false
